### 臺灣上市公司股票價格(含公司債)
### Taiwan listed stock's price.

In [1]:
from pandas.core.frame import DataFrame
import requests
import pandas as pd

def get_stock_price(date:str) -> DataFrame:

    # get csv file
    url = 'https://www.twse.com.tw/exchangeReport'
    url += f'/MI_INDEX?response=csv&date={date}&type=ALL'
    res = requests.get(url)
    data = res.text

    # cleaning process
    cleaned_data = []
    for da in data.split('\n'):
        if len(da.split('","')) == 16 and da.split('","')[0][0] != '=':
            cleaned_data.append([ele.replace('",\r','').replace('"','') 
                                for ele in da.split('","')])
            
    # output
    df = pd.DataFrame(cleaned_data, columns = cleaned_data[0])
    df = df.set_index('證券代號')[1:]

    return df

In [2]:
get_stock_price('20210908')

,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,,,,,,,,,,,,,,,
1101,台泥,"12,388,795","6,135","601,734,602",48.70,48.95,48.20,48.55,-,0.20,48.55,56,48.60,505,11.93
1101B,台泥乙特,"10,152",12,"520,707",51.30,51.70,51.20,51.40,-,0.20,51.20,1,51.40,49,0.00
1102,亞泥,"6,774,957","3,418","303,131,698",45.10,45.15,44.55,44.75,-,0.40,44.70,5,44.75,113,8.86
1103,嘉泥,"4,062,701",997,"83,777,303",20.70,20.80,20.30,20.30,X,0.00,20.30,22,20.35,7,8.46
1104,環泥,"431,804",253,"9,023,194",21.10,21.10,20.80,20.85,-,0.15,20.85,6,20.90,6,10.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,新麗,"353,403",230,"7,595,871",21.15,22.10,20.90,22.00,+,1.00,21.60,1,22.00,4,24.18
9945,潤泰新,"12,713,482","7,633","958,245,019",76.50,76.70,74.60,75.10,-,1.00,75.10,62,75.20,15,7.75
9946,三發地產,"394,630",162,"6,561,647",17.25,17.25,16.50,16.50,-,0.50,16.45,18,16.50,5,75.00
9955,佳龍,"87,608",174,"1,464,222",16.85,16.85,16.55,16.55,-,0.25,16.55,11,16.60,5,0.00
9958,世紀鋼,"2,708,565","1,897","281,865,006",106.50,106.50,102.50,103.00,-,4.00,102.50,83,103.00,31,18.69